tronprotocol/protocol

api/api.proto
core/Contract.proto
core/Tron.proto

feature: add api and contract.

---

api/api.proto

fix: rename.

---

api/api.proto
core/Contract.proto
core/Tron.proto

Rename ParticipateAssetIssueContract.

fix: rename ParticipateAssetIssueContract.

---

core/Contract.proto

change amount type to int64.

---

api/api.proto

add GetAccontByAddress.

---

api/api.proto

add TotalTransaction method return all TotalTransaction amount.

add TotalTransaction method return all TotalTransaction amount.

---

api/api.proto
core/Tron.proto

add GetDynamicProperties rpc api

add GetDynamicProperties rpc api

---

.travis.yml
README.md
api/api.proto
core/Contract.proto
core/Discover.proto
core/Tron.proto
core/TronInventoryItems.proto
install-googleapis.sh
install-protobuf.sh

Tron proxy

---

api/api.proto

feature:add Database api Service.

---

api/api.proto

fix: return type.

---

api/api.proto
core/Contract.proto
core/Tron.proto

add frozen balance in account;
add allowance in account(for witness)

Add frozen and allowance

---

api/api.proto

feat: add fullnode GRPC.

---

api/api.proto
core/Tron.proto

Add witness committee

---

api/api.proto

add grpc return type:server busy

add grpc return type:server busy

---

api/api.proto

Delete useless api and add get url binding.

feat: delete useless api and add get url binding.

---

api/api.proto

rm api
GetAssetIssueListByTimestamp
GetAssetIssueByAccount
GetAssetIssueByName
TotalTransaction
GetTransactionById
GetTransactionsByTimestamp
GetTransactionsByTimestampCount
GetTransactionsFromThisCount
GetTransactionsToThisCount

feat: remove api.

---

api/api.proto
core/Tron.proto

add getTransactionSign

---

api/api.proto

feat: add api.

---

api/api.proto
core/Contract.proto
core/Tron.proto

add support for vm

---

core/Tron.proto

remove unused proto item: Account.codeHash

remove unused proto item: Account.codeHash

---

core/Contract.proto
core/Tron.proto

Vm refactor api

---

core/Contract.proto
core/Tron.proto

Update proto v3.6.0

---

api/api.proto

add call constant in soliditynode

add call constant in soliditynode

---

api/api.proto

What does this PR do?
Add APIs for shielded TRC20 transaction.
Why are these changes required?
Add APIs for shielded TRC20 transaction.
This PR has been tested by:
Manual Testing
Follow up

add APIs for shielded TRC20 transaction

---

core/contract/market_contract.proto

typo: remove unused param for dex

typo: remove unused param

---

api/api.proto
core/Tron.proto

merge java-tron/protocol 4.1.2

merge java-tron/protocol 4.1.2

---

core/Tron.proto

add receiptsRoot to block header

add receiptsRoot to block header

---

core/Tron.proto

rm receipts root

---

api/api.proto
core/Tron.proto
core/contract/smart_contract.proto

- Add `string extra` field to InternalTransaction
- Add `int64 energy_used` field to TransactionExtention
- Add `EntryType Error` enum to ABI.Entry

Adapt to java_tron-v4.3

---

api/api.proto
core/Tron.proto
core/contract/common.proto
core/contract/smart_contract.proto

add AccountAsset protobuf

---

install-googleapis.sh

1. modify googleapis-common-protos-0.0.3.jar download url

feat(shell): modify shell url

---

api/api.proto

**What does this PR do?**
Add three interfaces for the new stake model.
**Why are these changes required?**
**This PR has been tested by:**
- Unit Tests
- Manual Testing
**Follow up**
**Extra details**

feat(freezeV2): add three interfaces for the new stake model

---

api/api.proto

**What does this PR do?**
add one interface for new stake model
**Why are these changes required?**
**This PR has been tested by:**
- Unit Tests
- Manual Testing
**Follow up**
**Extra details**

feat(new stake): add one interface for new stake model

---

api/api.proto
core/Tron.proto
core/contract/balance_contract.proto

**What does this PR do?**
Add some protocols and contracts
Add multiple interfaces for stake2.0
**Why are these changes required?**
**This PR has been tested by:**
- Unit Tests
- Manual Testing
**Follow up**
**Extra details**

feat(freezeV2): merge feature ‘stake 2.0’ into release v4.7.0

---

api/api.proto
core/Tron.proto
core/contract/smart_contract.proto

1. add api.proto
2. Tron.proto
3. smart_contract.proto

feat(stake): add api

---

api/api.proto
core/Tron.proto
core/contract/balance_contract.proto
core/contract/smart_contract.proto

Release v4.7.0

---

core/Tron.proto

**What does this PR do?**
optimize resource usage recovery logic
**Why are these changes required?**
optimize resource usage recovery logic
**This PR has been tested by:**
- Unit Tests
- Manual Testing
**Follow up**
**Extra details**

fix(freezeV2): optimize resource usage recovery logic
